# Generated by Django 3.2.3 on 2022-03-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='reset', max_length=50)),
                ('pause_time', models.CharField(max_length=50, null=True)),
                ('time_to_end', models.TimeField(null=True)),
            ],
        ),
    ]
