# Generated by Django 3.2.3 on 2022-03-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switches',
            name='time_to_end',
            field=models.DateTimeField(null=True),
        ),
    ]
