# Generated by Django 3.2.3 on 2022-04-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0002_alter_switches_time_to_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='switches',
            name='user',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
