# Generated by Django 3.2.3 on 2022-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0003_switches_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switches',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
