# Generated by Django 3.2.3 on 2022-04-06 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0004_alter_switches_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('time_left', models.CharField(max_length=50, null=True)),
                ('station_no', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
            ],
        ),
        migrations.RemoveField(
            model_name='switches',
            name='user',
        ),
        migrations.AddField(
            model_name='switches',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
