# Generated by Django 3.2.3 on 2022-04-11 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0006_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(auto_now_add=True)),
                ('total_time', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='switches',
            name='ttl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='log_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switches.time'),
        ),
    ]
